tools:
    php_cs_fixer: true
    php_cpd: true
    php_code_sniffer:
        config:
            standard: PSR2
    php_mess_detector: true
    php_analyzer: true
    sensiolabs_security_checker: true